# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rbnuria/ParchisIA-23

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rbnuria/ParchisIA-23

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rbnuria/ParchisIA-23/CMakeFiles /home/rbnuria/ParchisIA-23/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rbnuria/ParchisIA-23/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Connection

# Build rule for target.
Connection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Connection
.PHONY : Connection

# fast build rule for target.
Connection/fast:
	$(MAKE) -f CMakeFiles/Connection.dir/build.make CMakeFiles/Connection.dir/build
.PHONY : Connection/fast

#=============================================================================
# Target rules for targets named SpriteAnimator

# Build rule for target.
SpriteAnimator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpriteAnimator
.PHONY : SpriteAnimator

# fast build rule for target.
SpriteAnimator/fast:
	$(MAKE) -f CMakeFiles/SpriteAnimator.dir/build.make CMakeFiles/SpriteAnimator.dir/build
.PHONY : SpriteAnimator/fast

#=============================================================================
# Target rules for targets named GUIPlayer

# Build rule for target.
GUIPlayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GUIPlayer
.PHONY : GUIPlayer

# fast build rule for target.
GUIPlayer/fast:
	$(MAKE) -f CMakeFiles/GUIPlayer.dir/build.make CMakeFiles/GUIPlayer.dir/build
.PHONY : GUIPlayer/fast

#=============================================================================
# Target rules for targets named Button

# Build rule for target.
Button: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Button
.PHONY : Button

# fast build rule for target.
Button/fast:
	$(MAKE) -f CMakeFiles/Button.dir/build.make CMakeFiles/Button.dir/build
.PHONY : Button/fast

#=============================================================================
# Target rules for targets named Ninja

# Build rule for target.
Ninja: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Ninja
.PHONY : Ninja

# fast build rule for target.
Ninja/fast:
	$(MAKE) -f CMakeFiles/Ninja.dir/build.make CMakeFiles/Ninja.dir/build
.PHONY : Ninja/fast

#=============================================================================
# Target rules for targets named AIPlayer

# Build rule for target.
AIPlayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AIPlayer
.PHONY : AIPlayer

# fast build rule for target.
AIPlayer/fast:
	$(MAKE) -f CMakeFiles/AIPlayer.dir/build.make CMakeFiles/AIPlayer.dir/build
.PHONY : AIPlayer/fast

#=============================================================================
# Target rules for targets named ExplosionSprite

# Build rule for target.
ExplosionSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExplosionSprite
.PHONY : ExplosionSprite

# fast build rule for target.
ExplosionSprite/fast:
	$(MAKE) -f CMakeFiles/ExplosionSprite.dir/build.make CMakeFiles/ExplosionSprite.dir/build
.PHONY : ExplosionSprite/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named Piece

# Build rule for target.
Piece: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Piece
.PHONY : Piece

# fast build rule for target.
Piece/fast:
	$(MAKE) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/build
.PHONY : Piece/fast

#=============================================================================
# Target rules for targets named ParchisGame

# Build rule for target.
ParchisGame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParchisGame
.PHONY : ParchisGame

# fast build rule for target.
ParchisGame/fast:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/build
.PHONY : ParchisGame/fast

#=============================================================================
# Target rules for targets named RemotePlayer

# Build rule for target.
RemotePlayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RemotePlayer
.PHONY : RemotePlayer

# fast build rule for target.
RemotePlayer/fast:
	$(MAKE) -f CMakeFiles/RemotePlayer.dir/build.make CMakeFiles/RemotePlayer.dir/build
.PHONY : RemotePlayer/fast

#=============================================================================
# Target rules for targets named Dice

# Build rule for target.
Dice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dice
.PHONY : Dice

# fast build rule for target.
Dice/fast:
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/build
.PHONY : Dice/fast

#=============================================================================
# Target rules for targets named Board

# Build rule for target.
Board: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Board
.PHONY : Board

# fast build rule for target.
Board/fast:
	$(MAKE) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/build
.PHONY : Board/fast

#=============================================================================
# Target rules for targets named ParchisGUI

# Build rule for target.
ParchisGUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ParchisGUI
.PHONY : ParchisGUI

# fast build rule for target.
ParchisGUI/fast:
	$(MAKE) -f CMakeFiles/ParchisGUI.dir/build.make CMakeFiles/ParchisGUI.dir/build
.PHONY : ParchisGUI/fast

#=============================================================================
# Target rules for targets named BoardSprite

# Build rule for target.
BoardSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BoardSprite
.PHONY : BoardSprite

# fast build rule for target.
BoardSprite/fast:
	$(MAKE) -f CMakeFiles/BoardSprite.dir/build.make CMakeFiles/BoardSprite.dir/build
.PHONY : BoardSprite/fast

#=============================================================================
# Target rules for targets named SpecialItemSprite

# Build rule for target.
SpecialItemSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SpecialItemSprite
.PHONY : SpecialItemSprite

# fast build rule for target.
SpecialItemSprite/fast:
	$(MAKE) -f CMakeFiles/SpecialItemSprite.dir/build.make CMakeFiles/SpecialItemSprite.dir/build
.PHONY : SpecialItemSprite/fast

#=============================================================================
# Target rules for targets named BoardTrapSprite

# Build rule for target.
BoardTrapSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BoardTrapSprite
.PHONY : BoardTrapSprite

# fast build rule for target.
BoardTrapSprite/fast:
	$(MAKE) -f CMakeFiles/BoardTrapSprite.dir/build.make CMakeFiles/BoardTrapSprite.dir/build
.PHONY : BoardTrapSprite/fast

#=============================================================================
# Target rules for targets named BoardTrap

# Build rule for target.
BoardTrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BoardTrap
.PHONY : BoardTrap

# fast build rule for target.
BoardTrap/fast:
	$(MAKE) -f CMakeFiles/BoardTrap.dir/build.make CMakeFiles/BoardTrap.dir/build
.PHONY : BoardTrap/fast

#=============================================================================
# Target rules for targets named Parchis

# Build rule for target.
Parchis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Parchis
.PHONY : Parchis

# fast build rule for target.
Parchis/fast:
	$(MAKE) -f CMakeFiles/Parchis.dir/build.make CMakeFiles/Parchis.dir/build
.PHONY : Parchis/fast

#=============================================================================
# Target rules for targets named ClickableSprite

# Build rule for target.
ClickableSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClickableSprite
.PHONY : ClickableSprite

# fast build rule for target.
ClickableSprite/fast:
	$(MAKE) -f CMakeFiles/ClickableSprite.dir/build.make CMakeFiles/ClickableSprite.dir/build
.PHONY : ClickableSprite/fast

#=============================================================================
# Target rules for targets named GameSelector

# Build rule for target.
GameSelector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameSelector
.PHONY : GameSelector

# fast build rule for target.
GameSelector/fast:
	$(MAKE) -f CMakeFiles/GameSelector.dir/build.make CMakeFiles/GameSelector.dir/build
.PHONY : GameSelector/fast

#=============================================================================
# Target rules for targets named DiceSprite

# Build rule for target.
DiceSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DiceSprite
.PHONY : DiceSprite

# fast build rule for target.
DiceSprite/fast:
	$(MAKE) -f CMakeFiles/DiceSprite.dir/build.make CMakeFiles/DiceSprite.dir/build
.PHONY : DiceSprite/fast

#=============================================================================
# Target rules for targets named Player

# Build rule for target.
Player: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Player
.PHONY : Player

# fast build rule for target.
Player/fast:
	$(MAKE) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/build
.PHONY : Player/fast

#=============================================================================
# Target rules for targets named PieceSprite

# Build rule for target.
PieceSprite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PieceSprite
.PHONY : PieceSprite

# fast build rule for target.
PieceSprite/fast:
	$(MAKE) -f CMakeFiles/PieceSprite.dir/build.make CMakeFiles/PieceSprite.dir/build
.PHONY : PieceSprite/fast

src/AIPlayer.o: src/AIPlayer.cpp.o

.PHONY : src/AIPlayer.o

# target to build an object file
src/AIPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/AIPlayer.dir/build.make CMakeFiles/AIPlayer.dir/src/AIPlayer.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/AIPlayer.cpp.o
.PHONY : src/AIPlayer.cpp.o

src/AIPlayer.i: src/AIPlayer.cpp.i

.PHONY : src/AIPlayer.i

# target to preprocess a source file
src/AIPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/AIPlayer.dir/build.make CMakeFiles/AIPlayer.dir/src/AIPlayer.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/AIPlayer.cpp.i
.PHONY : src/AIPlayer.cpp.i

src/AIPlayer.s: src/AIPlayer.cpp.s

.PHONY : src/AIPlayer.s

# target to generate assembly for a file
src/AIPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/AIPlayer.dir/build.make CMakeFiles/AIPlayer.dir/src/AIPlayer.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/AIPlayer.cpp.s
.PHONY : src/AIPlayer.cpp.s

src/Board.o: src/Board.cpp.o

.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Board.cpp.o
	$(MAKE) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i

.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Board.cpp.i
	$(MAKE) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s

.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Board.cpp.s
	$(MAKE) -f CMakeFiles/Board.dir/build.make CMakeFiles/Board.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/BoardSprite.o: src/BoardSprite.cpp.o

.PHONY : src/BoardSprite.o

# target to build an object file
src/BoardSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardSprite.cpp.o
	$(MAKE) -f CMakeFiles/BoardSprite.dir/build.make CMakeFiles/BoardSprite.dir/src/BoardSprite.cpp.o
.PHONY : src/BoardSprite.cpp.o

src/BoardSprite.i: src/BoardSprite.cpp.i

.PHONY : src/BoardSprite.i

# target to preprocess a source file
src/BoardSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardSprite.cpp.i
	$(MAKE) -f CMakeFiles/BoardSprite.dir/build.make CMakeFiles/BoardSprite.dir/src/BoardSprite.cpp.i
.PHONY : src/BoardSprite.cpp.i

src/BoardSprite.s: src/BoardSprite.cpp.s

.PHONY : src/BoardSprite.s

# target to generate assembly for a file
src/BoardSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardSprite.cpp.s
	$(MAKE) -f CMakeFiles/BoardSprite.dir/build.make CMakeFiles/BoardSprite.dir/src/BoardSprite.cpp.s
.PHONY : src/BoardSprite.cpp.s

src/BoardTrap.o: src/BoardTrap.cpp.o

.PHONY : src/BoardTrap.o

# target to build an object file
src/BoardTrap.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardTrap.cpp.o
	$(MAKE) -f CMakeFiles/BoardTrap.dir/build.make CMakeFiles/BoardTrap.dir/src/BoardTrap.cpp.o
.PHONY : src/BoardTrap.cpp.o

src/BoardTrap.i: src/BoardTrap.cpp.i

.PHONY : src/BoardTrap.i

# target to preprocess a source file
src/BoardTrap.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardTrap.cpp.i
	$(MAKE) -f CMakeFiles/BoardTrap.dir/build.make CMakeFiles/BoardTrap.dir/src/BoardTrap.cpp.i
.PHONY : src/BoardTrap.cpp.i

src/BoardTrap.s: src/BoardTrap.cpp.s

.PHONY : src/BoardTrap.s

# target to generate assembly for a file
src/BoardTrap.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardTrap.cpp.s
	$(MAKE) -f CMakeFiles/BoardTrap.dir/build.make CMakeFiles/BoardTrap.dir/src/BoardTrap.cpp.s
.PHONY : src/BoardTrap.cpp.s

src/BoardTrapSprite.o: src/BoardTrapSprite.cpp.o

.PHONY : src/BoardTrapSprite.o

# target to build an object file
src/BoardTrapSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardTrapSprite.cpp.o
	$(MAKE) -f CMakeFiles/BoardTrapSprite.dir/build.make CMakeFiles/BoardTrapSprite.dir/src/BoardTrapSprite.cpp.o
.PHONY : src/BoardTrapSprite.cpp.o

src/BoardTrapSprite.i: src/BoardTrapSprite.cpp.i

.PHONY : src/BoardTrapSprite.i

# target to preprocess a source file
src/BoardTrapSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardTrapSprite.cpp.i
	$(MAKE) -f CMakeFiles/BoardTrapSprite.dir/build.make CMakeFiles/BoardTrapSprite.dir/src/BoardTrapSprite.cpp.i
.PHONY : src/BoardTrapSprite.cpp.i

src/BoardTrapSprite.s: src/BoardTrapSprite.cpp.s

.PHONY : src/BoardTrapSprite.s

# target to generate assembly for a file
src/BoardTrapSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/BoardTrapSprite.cpp.s
	$(MAKE) -f CMakeFiles/BoardTrapSprite.dir/build.make CMakeFiles/BoardTrapSprite.dir/src/BoardTrapSprite.cpp.s
.PHONY : src/BoardTrapSprite.cpp.s

src/Button.o: src/Button.cpp.o

.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/Button.dir/build.make CMakeFiles/Button.dir/src/Button.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i

.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/Button.dir/build.make CMakeFiles/Button.dir/src/Button.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s

.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/Button.dir/build.make CMakeFiles/Button.dir/src/Button.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/ClickableSprite.o: src/ClickableSprite.cpp.o

.PHONY : src/ClickableSprite.o

# target to build an object file
src/ClickableSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ClickableSprite.cpp.o
	$(MAKE) -f CMakeFiles/ClickableSprite.dir/build.make CMakeFiles/ClickableSprite.dir/src/ClickableSprite.cpp.o
.PHONY : src/ClickableSprite.cpp.o

src/ClickableSprite.i: src/ClickableSprite.cpp.i

.PHONY : src/ClickableSprite.i

# target to preprocess a source file
src/ClickableSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ClickableSprite.cpp.i
	$(MAKE) -f CMakeFiles/ClickableSprite.dir/build.make CMakeFiles/ClickableSprite.dir/src/ClickableSprite.cpp.i
.PHONY : src/ClickableSprite.cpp.i

src/ClickableSprite.s: src/ClickableSprite.cpp.s

.PHONY : src/ClickableSprite.s

# target to generate assembly for a file
src/ClickableSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ClickableSprite.cpp.s
	$(MAKE) -f CMakeFiles/ClickableSprite.dir/build.make CMakeFiles/ClickableSprite.dir/src/ClickableSprite.cpp.s
.PHONY : src/ClickableSprite.cpp.s

src/Connection.o: src/Connection.cpp.o

.PHONY : src/Connection.o

# target to build an object file
src/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/Connection.dir/build.make CMakeFiles/Connection.dir/src/Connection.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Connection.cpp.o
.PHONY : src/Connection.cpp.o

src/Connection.i: src/Connection.cpp.i

.PHONY : src/Connection.i

# target to preprocess a source file
src/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/Connection.dir/build.make CMakeFiles/Connection.dir/src/Connection.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Connection.cpp.i
.PHONY : src/Connection.cpp.i

src/Connection.s: src/Connection.cpp.s

.PHONY : src/Connection.s

# target to generate assembly for a file
src/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/Connection.dir/build.make CMakeFiles/Connection.dir/src/Connection.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Connection.cpp.s
.PHONY : src/Connection.cpp.s

src/Dice.o: src/Dice.cpp.o

.PHONY : src/Dice.o

# target to build an object file
src/Dice.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Dice.cpp.o
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/src/Dice.cpp.o
.PHONY : src/Dice.cpp.o

src/Dice.i: src/Dice.cpp.i

.PHONY : src/Dice.i

# target to preprocess a source file
src/Dice.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Dice.cpp.i
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/src/Dice.cpp.i
.PHONY : src/Dice.cpp.i

src/Dice.s: src/Dice.cpp.s

.PHONY : src/Dice.s

# target to generate assembly for a file
src/Dice.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Dice.cpp.s
	$(MAKE) -f CMakeFiles/Dice.dir/build.make CMakeFiles/Dice.dir/src/Dice.cpp.s
.PHONY : src/Dice.cpp.s

src/DiceSprite.o: src/DiceSprite.cpp.o

.PHONY : src/DiceSprite.o

# target to build an object file
src/DiceSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/DiceSprite.cpp.o
	$(MAKE) -f CMakeFiles/DiceSprite.dir/build.make CMakeFiles/DiceSprite.dir/src/DiceSprite.cpp.o
.PHONY : src/DiceSprite.cpp.o

src/DiceSprite.i: src/DiceSprite.cpp.i

.PHONY : src/DiceSprite.i

# target to preprocess a source file
src/DiceSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/DiceSprite.cpp.i
	$(MAKE) -f CMakeFiles/DiceSprite.dir/build.make CMakeFiles/DiceSprite.dir/src/DiceSprite.cpp.i
.PHONY : src/DiceSprite.cpp.i

src/DiceSprite.s: src/DiceSprite.cpp.s

.PHONY : src/DiceSprite.s

# target to generate assembly for a file
src/DiceSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/DiceSprite.cpp.s
	$(MAKE) -f CMakeFiles/DiceSprite.dir/build.make CMakeFiles/DiceSprite.dir/src/DiceSprite.cpp.s
.PHONY : src/DiceSprite.cpp.s

src/ExplosionSprite.o: src/ExplosionSprite.cpp.o

.PHONY : src/ExplosionSprite.o

# target to build an object file
src/ExplosionSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ExplosionSprite.dir/build.make CMakeFiles/ExplosionSprite.dir/src/ExplosionSprite.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ExplosionSprite.cpp.o
.PHONY : src/ExplosionSprite.cpp.o

src/ExplosionSprite.i: src/ExplosionSprite.cpp.i

.PHONY : src/ExplosionSprite.i

# target to preprocess a source file
src/ExplosionSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ExplosionSprite.dir/build.make CMakeFiles/ExplosionSprite.dir/src/ExplosionSprite.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ExplosionSprite.cpp.i
.PHONY : src/ExplosionSprite.cpp.i

src/ExplosionSprite.s: src/ExplosionSprite.cpp.s

.PHONY : src/ExplosionSprite.s

# target to generate assembly for a file
src/ExplosionSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ExplosionSprite.dir/build.make CMakeFiles/ExplosionSprite.dir/src/ExplosionSprite.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ExplosionSprite.cpp.s
.PHONY : src/ExplosionSprite.cpp.s

src/GUIPlayer.o: src/GUIPlayer.cpp.o

.PHONY : src/GUIPlayer.o

# target to build an object file
src/GUIPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/GUIPlayer.dir/build.make CMakeFiles/GUIPlayer.dir/src/GUIPlayer.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/GUIPlayer.cpp.o
.PHONY : src/GUIPlayer.cpp.o

src/GUIPlayer.i: src/GUIPlayer.cpp.i

.PHONY : src/GUIPlayer.i

# target to preprocess a source file
src/GUIPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/GUIPlayer.dir/build.make CMakeFiles/GUIPlayer.dir/src/GUIPlayer.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/GUIPlayer.cpp.i
.PHONY : src/GUIPlayer.cpp.i

src/GUIPlayer.s: src/GUIPlayer.cpp.s

.PHONY : src/GUIPlayer.s

# target to generate assembly for a file
src/GUIPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/GUIPlayer.dir/build.make CMakeFiles/GUIPlayer.dir/src/GUIPlayer.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/GUIPlayer.cpp.s
.PHONY : src/GUIPlayer.cpp.s

src/GameSelector.o: src/GameSelector.cpp.o

.PHONY : src/GameSelector.o

# target to build an object file
src/GameSelector.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/GameSelector.cpp.o
	$(MAKE) -f CMakeFiles/GameSelector.dir/build.make CMakeFiles/GameSelector.dir/src/GameSelector.cpp.o
.PHONY : src/GameSelector.cpp.o

src/GameSelector.i: src/GameSelector.cpp.i

.PHONY : src/GameSelector.i

# target to preprocess a source file
src/GameSelector.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/GameSelector.cpp.i
	$(MAKE) -f CMakeFiles/GameSelector.dir/build.make CMakeFiles/GameSelector.dir/src/GameSelector.cpp.i
.PHONY : src/GameSelector.cpp.i

src/GameSelector.s: src/GameSelector.cpp.s

.PHONY : src/GameSelector.s

# target to generate assembly for a file
src/GameSelector.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/GameSelector.cpp.s
	$(MAKE) -f CMakeFiles/GameSelector.dir/build.make CMakeFiles/GameSelector.dir/src/GameSelector.cpp.s
.PHONY : src/GameSelector.cpp.s

src/Ninja.o: src/Ninja.cpp.o

.PHONY : src/Ninja.o

# target to build an object file
src/Ninja.cpp.o:
	$(MAKE) -f CMakeFiles/Ninja.dir/build.make CMakeFiles/Ninja.dir/src/Ninja.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Ninja.cpp.o
.PHONY : src/Ninja.cpp.o

src/Ninja.i: src/Ninja.cpp.i

.PHONY : src/Ninja.i

# target to preprocess a source file
src/Ninja.cpp.i:
	$(MAKE) -f CMakeFiles/Ninja.dir/build.make CMakeFiles/Ninja.dir/src/Ninja.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Ninja.cpp.i
.PHONY : src/Ninja.cpp.i

src/Ninja.s: src/Ninja.cpp.s

.PHONY : src/Ninja.s

# target to generate assembly for a file
src/Ninja.cpp.s:
	$(MAKE) -f CMakeFiles/Ninja.dir/build.make CMakeFiles/Ninja.dir/src/Ninja.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Ninja.cpp.s
.PHONY : src/Ninja.cpp.s

src/Parchis.o: src/Parchis.cpp.o

.PHONY : src/Parchis.o

# target to build an object file
src/Parchis.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Parchis.cpp.o
	$(MAKE) -f CMakeFiles/Parchis.dir/build.make CMakeFiles/Parchis.dir/src/Parchis.cpp.o
.PHONY : src/Parchis.cpp.o

src/Parchis.i: src/Parchis.cpp.i

.PHONY : src/Parchis.i

# target to preprocess a source file
src/Parchis.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Parchis.cpp.i
	$(MAKE) -f CMakeFiles/Parchis.dir/build.make CMakeFiles/Parchis.dir/src/Parchis.cpp.i
.PHONY : src/Parchis.cpp.i

src/Parchis.s: src/Parchis.cpp.s

.PHONY : src/Parchis.s

# target to generate assembly for a file
src/Parchis.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Parchis.cpp.s
	$(MAKE) -f CMakeFiles/Parchis.dir/build.make CMakeFiles/Parchis.dir/src/Parchis.cpp.s
.PHONY : src/Parchis.cpp.s

src/ParchisGUI.o: src/ParchisGUI.cpp.o

.PHONY : src/ParchisGUI.o

# target to build an object file
src/ParchisGUI.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ParchisGUI.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGUI.dir/build.make CMakeFiles/ParchisGUI.dir/src/ParchisGUI.cpp.o
.PHONY : src/ParchisGUI.cpp.o

src/ParchisGUI.i: src/ParchisGUI.cpp.i

.PHONY : src/ParchisGUI.i

# target to preprocess a source file
src/ParchisGUI.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ParchisGUI.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGUI.dir/build.make CMakeFiles/ParchisGUI.dir/src/ParchisGUI.cpp.i
.PHONY : src/ParchisGUI.cpp.i

src/ParchisGUI.s: src/ParchisGUI.cpp.s

.PHONY : src/ParchisGUI.s

# target to generate assembly for a file
src/ParchisGUI.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/ParchisGUI.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGUI.dir/build.make CMakeFiles/ParchisGUI.dir/src/ParchisGUI.cpp.s
.PHONY : src/ParchisGUI.cpp.s

src/Piece.o: src/Piece.cpp.o

.PHONY : src/Piece.o

# target to build an object file
src/Piece.cpp.o:
	$(MAKE) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/src/Piece.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Piece.cpp.o
.PHONY : src/Piece.cpp.o

src/Piece.i: src/Piece.cpp.i

.PHONY : src/Piece.i

# target to preprocess a source file
src/Piece.cpp.i:
	$(MAKE) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/src/Piece.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Piece.cpp.i
.PHONY : src/Piece.cpp.i

src/Piece.s: src/Piece.cpp.s

.PHONY : src/Piece.s

# target to generate assembly for a file
src/Piece.cpp.s:
	$(MAKE) -f CMakeFiles/Piece.dir/build.make CMakeFiles/Piece.dir/src/Piece.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Piece.cpp.s
.PHONY : src/Piece.cpp.s

src/PieceSprite.o: src/PieceSprite.cpp.o

.PHONY : src/PieceSprite.o

# target to build an object file
src/PieceSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/PieceSprite.cpp.o
	$(MAKE) -f CMakeFiles/PieceSprite.dir/build.make CMakeFiles/PieceSprite.dir/src/PieceSprite.cpp.o
.PHONY : src/PieceSprite.cpp.o

src/PieceSprite.i: src/PieceSprite.cpp.i

.PHONY : src/PieceSprite.i

# target to preprocess a source file
src/PieceSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/PieceSprite.cpp.i
	$(MAKE) -f CMakeFiles/PieceSprite.dir/build.make CMakeFiles/PieceSprite.dir/src/PieceSprite.cpp.i
.PHONY : src/PieceSprite.cpp.i

src/PieceSprite.s: src/PieceSprite.cpp.s

.PHONY : src/PieceSprite.s

# target to generate assembly for a file
src/PieceSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/PieceSprite.cpp.s
	$(MAKE) -f CMakeFiles/PieceSprite.dir/build.make CMakeFiles/PieceSprite.dir/src/PieceSprite.cpp.s
.PHONY : src/PieceSprite.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Player.cpp.o
	$(MAKE) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Player.cpp.i
	$(MAKE) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/Player.cpp.s
	$(MAKE) -f CMakeFiles/Player.dir/build.make CMakeFiles/Player.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/RectangularButton.o: src/RectangularButton.cpp.o

.PHONY : src/RectangularButton.o

# target to build an object file
src/RectangularButton.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/RectangularButton.cpp.o
.PHONY : src/RectangularButton.cpp.o

src/RectangularButton.i: src/RectangularButton.cpp.i

.PHONY : src/RectangularButton.i

# target to preprocess a source file
src/RectangularButton.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/RectangularButton.cpp.i
.PHONY : src/RectangularButton.cpp.i

src/RectangularButton.s: src/RectangularButton.cpp.s

.PHONY : src/RectangularButton.s

# target to generate assembly for a file
src/RectangularButton.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/RectangularButton.cpp.s
.PHONY : src/RectangularButton.cpp.s

src/RemotePlayer.o: src/RemotePlayer.cpp.o

.PHONY : src/RemotePlayer.o

# target to build an object file
src/RemotePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/RemotePlayer.cpp.o
	$(MAKE) -f CMakeFiles/RemotePlayer.dir/build.make CMakeFiles/RemotePlayer.dir/src/RemotePlayer.cpp.o
.PHONY : src/RemotePlayer.cpp.o

src/RemotePlayer.i: src/RemotePlayer.cpp.i

.PHONY : src/RemotePlayer.i

# target to preprocess a source file
src/RemotePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/RemotePlayer.cpp.i
	$(MAKE) -f CMakeFiles/RemotePlayer.dir/build.make CMakeFiles/RemotePlayer.dir/src/RemotePlayer.cpp.i
.PHONY : src/RemotePlayer.cpp.i

src/RemotePlayer.s: src/RemotePlayer.cpp.s

.PHONY : src/RemotePlayer.s

# target to generate assembly for a file
src/RemotePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/RemotePlayer.cpp.s
	$(MAKE) -f CMakeFiles/RemotePlayer.dir/build.make CMakeFiles/RemotePlayer.dir/src/RemotePlayer.cpp.s
.PHONY : src/RemotePlayer.cpp.s

src/SpecialItemSprite.o: src/SpecialItemSprite.cpp.o

.PHONY : src/SpecialItemSprite.o

# target to build an object file
src/SpecialItemSprite.cpp.o:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/SpecialItemSprite.cpp.o
	$(MAKE) -f CMakeFiles/SpecialItemSprite.dir/build.make CMakeFiles/SpecialItemSprite.dir/src/SpecialItemSprite.cpp.o
.PHONY : src/SpecialItemSprite.cpp.o

src/SpecialItemSprite.i: src/SpecialItemSprite.cpp.i

.PHONY : src/SpecialItemSprite.i

# target to preprocess a source file
src/SpecialItemSprite.cpp.i:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/SpecialItemSprite.cpp.i
	$(MAKE) -f CMakeFiles/SpecialItemSprite.dir/build.make CMakeFiles/SpecialItemSprite.dir/src/SpecialItemSprite.cpp.i
.PHONY : src/SpecialItemSprite.cpp.i

src/SpecialItemSprite.s: src/SpecialItemSprite.cpp.s

.PHONY : src/SpecialItemSprite.s

# target to generate assembly for a file
src/SpecialItemSprite.cpp.s:
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/SpecialItemSprite.cpp.s
	$(MAKE) -f CMakeFiles/SpecialItemSprite.dir/build.make CMakeFiles/SpecialItemSprite.dir/src/SpecialItemSprite.cpp.s
.PHONY : src/SpecialItemSprite.cpp.s

src/SpriteAnimator.o: src/SpriteAnimator.cpp.o

.PHONY : src/SpriteAnimator.o

# target to build an object file
src/SpriteAnimator.cpp.o:
	$(MAKE) -f CMakeFiles/SpriteAnimator.dir/build.make CMakeFiles/SpriteAnimator.dir/src/SpriteAnimator.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/SpriteAnimator.cpp.o
.PHONY : src/SpriteAnimator.cpp.o

src/SpriteAnimator.i: src/SpriteAnimator.cpp.i

.PHONY : src/SpriteAnimator.i

# target to preprocess a source file
src/SpriteAnimator.cpp.i:
	$(MAKE) -f CMakeFiles/SpriteAnimator.dir/build.make CMakeFiles/SpriteAnimator.dir/src/SpriteAnimator.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/SpriteAnimator.cpp.i
.PHONY : src/SpriteAnimator.cpp.i

src/SpriteAnimator.s: src/SpriteAnimator.cpp.s

.PHONY : src/SpriteAnimator.s

# target to generate assembly for a file
src/SpriteAnimator.cpp.s:
	$(MAKE) -f CMakeFiles/SpriteAnimator.dir/build.make CMakeFiles/SpriteAnimator.dir/src/SpriteAnimator.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/SpriteAnimator.cpp.s
.PHONY : src/SpriteAnimator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
	$(MAKE) -f CMakeFiles/ParchisGame.dir/build.make CMakeFiles/ParchisGame.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Connection"
	@echo "... SpriteAnimator"
	@echo "... GUIPlayer"
	@echo "... Button"
	@echo "... Ninja"
	@echo "... AIPlayer"
	@echo "... ExplosionSprite"
	@echo "... main"
	@echo "... Piece"
	@echo "... ParchisGame"
	@echo "... RemotePlayer"
	@echo "... Dice"
	@echo "... Board"
	@echo "... ParchisGUI"
	@echo "... BoardSprite"
	@echo "... SpecialItemSprite"
	@echo "... BoardTrapSprite"
	@echo "... BoardTrap"
	@echo "... Parchis"
	@echo "... ClickableSprite"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GameSelector"
	@echo "... DiceSprite"
	@echo "... Player"
	@echo "... PieceSprite"
	@echo "... src/AIPlayer.o"
	@echo "... src/AIPlayer.i"
	@echo "... src/AIPlayer.s"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/BoardSprite.o"
	@echo "... src/BoardSprite.i"
	@echo "... src/BoardSprite.s"
	@echo "... src/BoardTrap.o"
	@echo "... src/BoardTrap.i"
	@echo "... src/BoardTrap.s"
	@echo "... src/BoardTrapSprite.o"
	@echo "... src/BoardTrapSprite.i"
	@echo "... src/BoardTrapSprite.s"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/ClickableSprite.o"
	@echo "... src/ClickableSprite.i"
	@echo "... src/ClickableSprite.s"
	@echo "... src/Connection.o"
	@echo "... src/Connection.i"
	@echo "... src/Connection.s"
	@echo "... src/Dice.o"
	@echo "... src/Dice.i"
	@echo "... src/Dice.s"
	@echo "... src/DiceSprite.o"
	@echo "... src/DiceSprite.i"
	@echo "... src/DiceSprite.s"
	@echo "... src/ExplosionSprite.o"
	@echo "... src/ExplosionSprite.i"
	@echo "... src/ExplosionSprite.s"
	@echo "... src/GUIPlayer.o"
	@echo "... src/GUIPlayer.i"
	@echo "... src/GUIPlayer.s"
	@echo "... src/GameSelector.o"
	@echo "... src/GameSelector.i"
	@echo "... src/GameSelector.s"
	@echo "... src/Ninja.o"
	@echo "... src/Ninja.i"
	@echo "... src/Ninja.s"
	@echo "... src/Parchis.o"
	@echo "... src/Parchis.i"
	@echo "... src/Parchis.s"
	@echo "... src/ParchisGUI.o"
	@echo "... src/ParchisGUI.i"
	@echo "... src/ParchisGUI.s"
	@echo "... src/Piece.o"
	@echo "... src/Piece.i"
	@echo "... src/Piece.s"
	@echo "... src/PieceSprite.o"
	@echo "... src/PieceSprite.i"
	@echo "... src/PieceSprite.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/RectangularButton.o"
	@echo "... src/RectangularButton.i"
	@echo "... src/RectangularButton.s"
	@echo "... src/RemotePlayer.o"
	@echo "... src/RemotePlayer.i"
	@echo "... src/RemotePlayer.s"
	@echo "... src/SpecialItemSprite.o"
	@echo "... src/SpecialItemSprite.i"
	@echo "... src/SpecialItemSprite.s"
	@echo "... src/SpriteAnimator.o"
	@echo "... src/SpriteAnimator.i"
	@echo "... src/SpriteAnimator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

